### ISSUE TITLE
Edge Canary 最新版本，扩展没反应了

### ISSUE THREAD

**Issue by domeniczz** [zhmushan-zone/translator_extension#11]
edge版本 90.0.795.0，升级最新版本之后扩展没反应了，不知道是edge的问题还是扩展的问题

**Comment by zhmushan** [comment]
插件里的那几个开关每个都随便点几下试试.....这里其实是有 bug 的, 因为触发概率比较低, 我一直没有修, 不确定是不是这个问题引起的
