### ISSUE TITLE
支持阅读模式

### ISSUE THREAD

**Issue by yours57** [zhmushan-zone/translator_extension#13]
希望能支持在阅读模式下划词翻译，例如我用的 Circle 阅读模式，这样的话会便捷很多，谢谢了

**Comment by zhmushan** [comment]
阅读模式一般是把 JavaScript 禁用掉的, 所以没有办法支持.
举个简单的例子, 划词翻译在阅读模式看来, 等同于广告

**Comment by yours57** [comment]
昂，原来是这样，谢谢啦
