### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Rpower666** [zhmushan-zone/translator_extension#14]
好兄弟，为啥现在划词没有反应了？

**Comment by zhmushan** [comment]
https://github.com/zhmushan-zone/translator_extension/issues/5#issuecomment-686233168

试试按照这个看能不能修复

PS: 你这样描述 “xxx 为什么没有反应了”, 谁能定位到问题啊

**Comment by zhmushan** [comment]
再次确认是否能通过 https://github.com/zhmushan-zone/translator_extension/issues/15 中的方案修复
