### ISSUE TITLE
火狐又不能使用了

### ISSUE THREAD

**Issue by DeloresC** [zhmushan-zone/translator_extension#17]
火狐划词无反应，等待作者修复

**Comment by zhmushan** [comment]
验证后确实存在这个问题, 但我很早就不用火狐了, 一直都是用 Edge, 可能要等下周或下下周才有时间修

**Comment by DeloresC** [comment]
好的，不着急，感谢您的回复



在 2021-08-28 17:33:57，"木杉" ***@***.***> 写道：

验证后确实存在这个问题, 但我很早就不用火狐了, 一直都是用 Edge, 可能要等下周或下下周才有时间修

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhmushan** [comment]
@DeloresC https://github.com/zhmushan-zone/translator_extension/commit/873e823a271eceb0a4f8d0ccd4a9cca60bee5530 修复了
