### ISSUE TITLE
能否支持下chrome

### ISSUE THREAD

**Issue by peakliuz** [zhmushan-zone/translator_extension#20]

**Comment by zhmushan** [comment]
不支持 Chrome 的原因有以下两点：
1. Chrome 商店上架要交钱

**Comment by peakliuz** [comment]
不在chrome上架就行,我们自己手动安装

**Comment by zhmushan** [comment]
了解了，下次更新（计划本周六）提供支持 Chrome 的包和安装教程

**Comment by peakliuz** [comment]
> 大佬yyds 😁
一般用浏览器插件的用户,基本都可以自己解决问题的

**Comment by zhmushan** [comment]
https://github.com/zhmushan-zone/translator_extension/releases/tag/v1.2.8

增加了流水线用来自动上传最新的包, 用户可以自由下载安装在任意 chrome like 的浏览器上
