### ISSUE TITLE
不知道为什么就失效了

### ISSUE THREAD

**Issue by shungli923** [zhmushan-zone/translator_extension#25]
尝试了重启浏览器，重新启动插件，重新安装插件都不行。上午刚发现这个插件还欢喜呢，下午转眼就不行了....关键是找不到失效原因。

**Comment by zhmushan** [comment]
插件用的是 https://translate.google.cn 的 api，近期很多人说这个网站要被关了，我也发现了很不稳定，也有可能是 dns 污染的缘故。如果你遇到了插件不能用的情况，可以看看打开这个网站能不能正常翻译，如果不行的话，那就是不行了。

我昨天下午不能用了，今天又可以了。

**Comment by zhmushan** [comment]
如果这个网站可以访问的话，你把插件的3个开关都多点点就好了，这里有个 bug，我没时间查原因。

**Comment by Chu4nQ1n** [comment]
我的也是今天失效了，请问楼上的兄弟们解决了吗?

**Comment by arglone** [comment]
+1，10月1号失效了

**Comment by linjinkang** [comment]
2022/10/5
用不了

**Comment by yzw6deboom** [comment]
今天2022/10/7日还是用不了，重装多次点击依然无效，https://translate.google.cn/可以使用

**Comment by zhmushan** [comment]
兄弟们，对不住了，谷歌翻译退出中国了 #26

**Comment by yzw6deboom** [comment]
> 兄弟们，对不住了，谷歌翻译退出中国了 #26

感谢大佬的开发！

**Comment by zhmushan** [comment]
已经修复了，Edge还在审核，想抢先体验的可以直接在 https://github.com/zhmushan-zone/translator_extension/releases/tag/v1.2.9 下载

![image](https://user-images.githubusercontent.com/24505451/194692130-32a27586-3609-41bc-ac02-1bdf7ee9d81d.png)
