### ISSUE TITLE
2022/10/01 宣布本插件暂时失效（已修复）

### ISSUE THREAD

**Issue by zhmushan** [zhmushan-zone/translator_extension#26]
由于 https://translate.google.cn 正式宣布关闭，而本插件依赖其 API，于是失效。对于这个消息，我也很难受，因为作者也是插件的重度用户，我每一天都在使用这个插件。

后续有没有可能继续能用？我也不知道，可能我会：
1. 看看能不能接入别的翻译，如 DeepL。
2. 选择一个别人开发好的。

**Comment by aluopy** [comment]
大佬，接入别的翻译吧，我不想用别人的，就喜欢用你这个。

**Comment by zhmushan** [comment]
我发现了一个项目 https://github.com/EdgeTranslate/EdgeTranslate/blob/master/packages/translators/package.json
我抄一下

**Comment by zhmushan** [comment]
已经修复了，Edge还在审核，想抢先体验的可以直接在 https://github.com/zhmushan-zone/translator_extension/releases/tag/v1.2.9 下载

![image](https://user-images.githubusercontent.com/24505451/194692130-32a27586-3609-41bc-ac02-1bdf7ee9d81d.png)

**Comment by mod196** [comment]
特来祝贺, 终于又可以了,感谢大佬的开源奉献, 愿永远身心健康

**Comment by Ahai-8** [comment]
Firefox 应该用哪些文件打包？
我试着用 firefox 文件夹的文件，或者移出替换后整个文件夹的文件，两种情况打包成xpi，安装到浏览器的时候都提示文件已经损坏。
