### ISSUE TITLE
打印网页时，插件会在页面上留下提示小方框，哪怕页面上已经没有显示了。

### ISSUE THREAD

**Issue by TigerHall** [zhmushan-zone/translator_extension#28]
打印网页时，插件会在页面上留下提示小方框，哪怕页面上已经没有显示了。
如下图
![image](https://user-images.githubusercontent.com/45758097/194695030-107b8c6e-a8d8-43e2-b207-2a696651faaf.png)
![image](https://user-images.githubusercontent.com/45758097/194695048-41b1afe4-bd62-4875-9d05-3d149eb6bb3e.png)
![image](https://user-images.githubusercontent.com/45758097/194695063-5e101a63-0c27-4a8d-8842-8cee4fc08cbb.png)

网页中用css，控制print，给一个display：none应该就可以去掉了

**Comment by zhmushan** [comment]
修复了 https://github.com/zhmushan-zone/translator_extension/commit/f60c0e0e97418423909e9b577c2856e8c54922f5
