### ISSUE TITLE
小白请教安装问题

### ISSUE THREAD

**Issue by zhuangshilong** [zhmushan-zone/translator_extension#29]
大佬您好，下载您的release文件chrome后，在edge加载解压缩的扩展，显示此扩展有错误，求问我的步骤是不是有问题？
![111](https://user-images.githubusercontent.com/54500081/194975907-6fb27f24-d6fc-48b4-aa9e-cf4566214f64.png)

**Comment by TigerHall** [comment]
Edge已经更新了，直接更新就行了撒。

**Comment by TigerHall** [comment]
![image](https://user-images.githubusercontent.com/45758097/194980971-fc280ed2-eb13-4c2d-9224-5e8b143fa17c.png)

**Comment by TigerHall** [comment]
就是换了翻译API，翻译变得有点慢
感觉不如以前安逸了，哈哈哈

**Comment by zhmushan** [comment]
这个提示错误不用管，我会在 V2 被弃用前发布 V3

由于这个项目是我接触 Web 写的第一个项目，代码比较糟糕，新增功能很困难，但已经在重写了 #27 
重写后会修复大部分存留问题，manifest V3 会随着重写后一起更新，然后会添加其它国内的翻译源供用户自己选择。
