### ISSUE TITLE
问一下PDF划词翻译功能能实现不

### ISSUE THREAD

**Issue by linjinkang** [zhmushan-zone/translator_extension#30]
![image](https://user-images.githubusercontent.com/54579927/198880490-74b10fb7-074a-4571-b4fa-ec5bab9b2e98.png)

**Comment by zhmushan** [comment]
能肯定是能，但毕竟这个插件主要是为了满足我自己用，不是用户导向，我对这一块的需求不是很大，还没有去研究要咋搞。如果你比较急的话，可以试试https://github.com/EdgeTranslate/EdgeTranslate
或者直接传pdf到https://deepl.com
