### ISSUE TITLE
大佬以后可能出整页翻译吗

### ISSUE THREAD

**Issue by kaseeen** [zhmushan-zone/translator_extension#33]
隔壁侧边翻译没这边简洁

**Comment by zhmushan** [comment]
我不知道你想要的整页翻译是做到哪种程度的，我理解有这几种模式：
1. 浏览器自带的「右键」-> 「翻译」。不能中英对照，体验不好。
2. 在整页翻译的基础上，添加点击/选中译文，在合适的位置出现原文。体验好，但我能力有限，做不出来。

综上是我没有做整页翻译的原因。
