### ISSUE TITLE
edge浏览器上UI显示有问题

### ISSUE THREAD

**Issue by oyoyjun** [zhmushan-zone/translator_extension#35]
刚刚下载，打开拓展时就发现UI只显示了左边的一小部分，其他的文字都显示不出来

**Comment by zhmushan** [comment]
不仅仅是UI展示不出来，核心功能也失效了

**Comment by mod196** [comment]
![image](https://github.com/zhmushan-zone/translator_extension/assets/52056232/0ac2b6d4-0375-4dda-aeca-f0285930c3c7)

**Comment by BrickAZ** [comment]
完全用不了啊喂，只能看到四个框

**Comment by zhmushan** [comment]
> 完全用不了啊喂，只能看到四个框

失效了，建议用：
https://github.com/openai-translator/openai-translator
