### ISSUE TITLE
发现怎么忽然不能用了，其他人有这个情况吗？

### ISSUE THREAD

**Issue by TimzChen** [zhmushan-zone/translator_extension#5]
RT

**Comment by zhmushan** [comment]
我也有过, 不过很少出现, 我出现这个问题的时候, 一般:
- 同一段时间里过于频繁的使用, 这种过几个小时就正常了
- 被 Google 当作机器人了, 访问 translate.google.cn 输一下验证码就好了

**Comment by TimzChen** [comment]
> 
> 
> 我也有过, 不过很少出现, 我出现这个问题的时候, 一般:
> 
>     * 同一段时间里过于频繁的使用, 这种过几个小时就正常了
> 
>     * 被 Google 当作机器人了, 访问 translate.google.cn 输一下验证码就好了

我昨天一开机就不能用了，今天试了下还是不能用，打开 translate.google.cn 也没有提示需要输入验证码。

**Comment by zhmushan** [comment]
如果重装也解决不了问题的话, 加我qq远程帮你看看吧.....(账号可以发我公开的邮箱

**Comment by zhmushan** [comment]
结论: UISwitch is undefined
临时解决方案: 打开插件窗口后那些按钮随便按几下

等待修复

**Comment by DeloresC** [comment]
火狐已经快一个星期用不了了，为什么呢？edge还能用......等待修复中...
而且，经常划词没反应，需要刷新页面才行，这个问题大家有吗？

**Comment by zhmushan** [comment]
@DeloresC 
"Edge 要刷新页面才行" 我不确定是什么导致的
火狐我等等我马上修复一下

**Comment by zhmushan** [comment]
@DeloresC 火狐我提交了一个新的版本, 应该修复了, 这个issue我先关了, 如果还有别的问题的话你可以开新的issue, 在这个issue下回复会打扰到别人
