### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by domeniczz** [zhmushan-zone/translator_extension#8]
edge浏览器，有一个多礼拜不能用了，重装也没用，点击插件里面的按钮也没有，反正就是无论如何也不能再有效了

**Comment by zhmushan** [comment]
@domeniczz 确实有一个bug, 会使小部分人用不了(我这边没问题), 我很早就提交了修复补丁, 要怪就怪微软龟速审核吧

火狐1分钟上架, 微软要一两周

**Comment by zhmushan** [comment]
@domeniczz 检查一下1.2.6这个版本, 应该修复了
