### ISSUE TITLE
有一个问题，当包含%时翻译显示出现bug

### ISSUE THREAD

**Issue by DeloresC** [zhmushan-zone/translator_extension#9]
就像这样。
![图片](https://user-images.githubusercontent.com/44831388/102871401-5acc4480-4479-11eb-8aa0-c3738f37232a.png)

**Comment by zhmushan** [comment]
了解👌

**Comment by zhmushan** [comment]
@DeloresC 修复了, 火狐已经可以用了, 微软审核大概需要一个多礼拜
